id: P007875
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD137798
  title: རྗེ་བཙུན་ལམ་རིམ་པ་ངག་དབང་ཕུན་ཚོགས་ཀྱི་གསུང་འབུམ།
  author: ''
  volumes:
    4f90e1ec95cc45d79452c9b8dde1e115:
      image_group_id: I2PD18554
      title: ''
      volume_number: 1
      total_pages: 370
    071c97d063444cb2b1bfab622c0ddc3b:
      image_group_id: I2PD18555
      title: ''
      volume_number: 2
      total_pages: 460
    e1016a999d9b4b15bc0c9f21c7dd7cf5:
      image_group_id: I2PD18556
      title: ''
      volume_number: 3
      total_pages: 358
    7888d4d9951d4974ab5ca1369359ea22:
      image_group_id: I2PD18557
      title: ''
      volume_number: 4
      total_pages: 710
    80a778ccb317469fb6ba83057a63856b:
      image_group_id: I2PD18558
      title: ''
      volume_number: 5
      total_pages: 346
ebook_metadata:
  title: རྗེ་བཙུན་ལམ་རིམ་པ་ངག་དབང་ཕུན་ཚོགས་ཀྱི་གསུང་འབུམ།
  author: ''
  sku: P007875
  cover: cover.jpg
  layers:
  - pagination
