id: I83A34AAD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T03:19:16+00:00'
last_modified: '2022-06-09T06:55:10.274677+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137798
  title: རྗེ་བཙུན་ལམ་རིམ་པ་ངག་དབང་ཕུན་ཚོགས་ཀྱི་གསུང་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1233':
      image_group_id: I2PD18554
      title: Volume 1 of rje btsun lam rim pa ngag dbang phun tshogs kyi gsung 'bum/
      total_pages: 370
      order: 1
      base_file: 1233.txt
    A2E0:
      image_group_id: I2PD18555
      title: Volume 2 of rje btsun lam rim pa ngag dbang phun tshogs kyi gsung 'bum/
      total_pages: 460
      order: 2
      base_file: A2E0.txt
    A840:
      image_group_id: I2PD18556
      title: Volume 3 of rje btsun lam rim pa ngag dbang phun tshogs kyi gsung 'bum/
      total_pages: 358
      order: 3
      base_file: A840.txt
    '1015':
      image_group_id: I2PD18557
      title: Volume 4 of rje btsun lam rim pa ngag dbang phun tshogs kyi gsung 'bum/
      total_pages: 710
      order: 4
      base_file: 1015.txt
    '5719':
      image_group_id: I2PD18558
      title: Volume 5 of rje btsun lam rim pa ngag dbang phun tshogs kyi gsung 'bum/
      total_pages: 346
      order: 5
      base_file: 5719.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
